FORMAT: 1A
HOST: https://www.uponor.de/

# Uponor PRO App - API

Folalowing API is designated to be used with UPONOR PRO APP.

## News [/api/UponorInternet/Newslist/{?language,count}]

### Newslist [GET]

+ Parameters
    + language: `de-de` (string, required) - Language code in which should the news be displayed
    + count (number, optional) - Ammount of items in news

+ Response 200 (application/json)

        {
            status: "1",
            message: "News Get Successfully",
            news: [
                {
                    id: "{FBC4267C-DE68-4874-8AF6-57F551834718}",
                    title: "Zweimal auf dem Treppchen ",
                    description: "Bei einer Leserwahl des Fachportals haustec.de hat Uponor zwei hervorragende zweite Pl&auml;tze erreicht: einmal mit der Einzelraumregelung Smatrix Pulse und einmal mit dem Online-Konfigurator f&uuml;r Verteilerstationen von Heiz- und K&uuml;hlsystemen.&nbsp;",
                    mediaType: "image",
                    createDate: "2021-04-08",
                    mediaFile: "https://www.uponor.de/-/media/country-specific/dach-benelux/news/newsarticle/haustec-leserwahl/haustec-leserwahl-510x320.jpg?h=300&w=400&usecustomfunctions=1&centercrop=1&hash=235C6C1513E44BCDA18A2D2A2E96EFF67A019E92",
                    mediaFileThumb: "https://www.uponor.de/-/media/country-specific/dach-benelux/news/newsarticle/haustec-leserwahl/haustec-leserwahl-510x320.jpg?h=100&w=100&usecustomfunctions=1&centercrop=1&hash=73CDF9EC64556499B01BBFA8FE40B99ECE542579",
                    url: "https://www.uponor.de/unternehmen/news/newsartikel/2021-04-haustec-leserwahl",
                },
            ],
        }

+ Attributes
    + status (string) - Status number (1 = success | 0 = ??)
    + message (string) - Status message
    + news (array [News item]) - list of news items

## Sales Locator [/api/UponorInternet/SalesLocator/{?plz,type}]

+ Parameters
    + plz (number) - ??
    + type (number, optional) - ??

### Get some [GET]

+ Response 200 (application/json)
        
        {
            ItemName: "Sales Locator List"
            Values: [
                        {
                            Company: "Uponor GmbH",
                            IdNo: "67",
                            Person: "Sven Argo",
                            Street: "",
                            PoBox: "",
                            Zipcode: "16761",
                            City: "Hennigsdorf",
                            Region: "",
                            Country: "Deutschland",
                            Phone: "03302 201809",
                            Mobile: "0172 4077723",
                            Fax: "09521 690 99232",
                            Email: "sven.argo@uponor.com",
                            Web: "www.uponor.de",
                            Image: "/-/media/uponor-internet/professional-images/argo-sven.jpg",
                            MembershipStartColumn: "",
                            RoleId: "de-DE",
                            Plz: "1"
                        },
            ]    
        }


+ Attributes
    + ItemName (string) - Item name
    + Values (array [Sales locator item]) - list of news items


## Contacts [/api/UponorInternet/Contact{?language,type}]

+ Parameters
    + language: `de-de` (string, required) - Language code in which should the contacts be displayed
    + type (enum[string], optional) - Contact type filter
        + Members
            + `academy`
            + `uponorandmore`
            + `customerservice`
            + `technicalhotline`

### Get some [GET]

+ Response 200 (application/json)
        
        {
            Name: "Contact Service",
            IsoCode: "de-DE",
            Values: [
                {
                    ContactType: "academy",
                    ContactName: "Academy",
                    ContactPhone: "+ 49 800 7780050 ",
                    ContactFax: "",
                    ContactMobile: "",
                    ContactMailLink: {
                        LinkDescription: "academy@uponor.com",
                        Mailto: "academy@uponor.com",
                        ContactMailSubject: "Uponor Academy"
                    }
                }
            ],
        }
        
+ Attributes
    + Name (string) - Name
    + IsoCode (string) - Item iso code
    + Values (array [Contact item]) - List of contact service items


## Locators/Profesionals [/api/UponorInternet/Map/professionals{?type,language,updateDate}]

+ Parameters
    + language: `de-de` (string, required) - Language code in which should the content be displayed
    + type: `Dealer` (enum[string], required) - Profesional type filter
        + Members
            + `Dealer`
            + `Sales`
            + `Installer`

### Get some [GET]

+ Response 200 (application/json)
        
        {
            ItemName: "Germany Wholesaler",
            ItemCountry: "de-DE",
            Profesionals: [
                {
                    Name: "Neugart KG - Fachgroßhandel für Haustechnik",
                    StreetAddress: "Max-Planck-Straße 2",
                    ZipCode: "53773",
                    Municipality: "",
                    City: "Hennef",
                    Country: "",
                    Telephone: "+49 (0)2242-9050-0",
                    Mobile: "",
                    Fax: "",
                    Email: "",
                    WebAddress: "http://www.neugart-kg.de",
                    TypeName: "Großhändler",
                    TypeIcon: "wholesaler",
                    Specialities: [ ],
                    AdditionalInformation: '<img style="width:25px" src="https://www.uponor.de/images/Website/merchanicTypes/heat.png"/> Heizen/Kühlen<br/><img style="width:25px" src="https://www.uponor.de/images/Website/merchanicTypes/sani.png"/> Installation<br/><img style="width:25px" src="https://www.uponor.de/images/Website/merchanicTypes/supply.png"/> Versorgung',
                    Latitude: "50.7664873",
                    Longitude: "7.3171985"
                },
            ],
        }

+ Attributes
    + ItemName (string) - Name
    + ItemCountry (string) - Item country
    + Professionals (array [Profesionals locator item]) - List of professionals

## Downloadcenter [/api/UponorInternet/CatalogueDownloadList{?language,section,doc}]

+ Parameters
    + language: `de-de` (string, required) - Language code in which should the content be displayed
    + section: `BLD` (enum[string], optional) - Section type filter
        + Members
            + `BLD`
            + `Infra`
    + doc: `E9E99F72DDE3483C862B50A5A37A3BB4` (string, optional) - Document type filter

### Get some [GET]

+ Response 200 (application/json)
        
        {
            ItemName: "DownloadCenter",
            IsoCode: "de-DE",
            Profesionals: [
                {
                    BrochureID: "1089122",
                    Date: "12.03.2017",
                    Description: "Produktbroschüre",
                    DocumentType: "Produktbroschüren ",
                    DownloadLink: "https://www.uponor.de/-/media/country-specific/dach-benelux/downloadcenter-archiv/01-salesfolder-archiv/uponor-sf-fluvia-t-push-12-de-1089122-201703.pdf?v=b704c33d-e210-4027-a948-db59cd6154ec",
                    FileType: "pdf",
                    FileTypeIcon: "https://www.uponor.de/UponorInternet/Images/Mimetypes/pdf.png",
                    ItemID: "{8B77D29D-A19B-4154-A9F4-B40DB895E68D}",
                    NewIcon: "",
                    Size: "1.12MB",
                    Thumbnail: "https://www.uponor.de/-/media/uponor-internet/thumbnails/pdfs/8/8b77d29da19b4154a9f4b40db895e68d.jpg?h=360&w=250&usecustomfunctions=1&centercrop=1&hash=7B2718BE9ED854680F4BE604085983D83EC824AC",
                    Title: "Uponor Fluvia T Push-12 Kleinstpumpengruppen "
                },
            ],
        }

+ Attributes
    + Name (string) - Name
    + IsoCode (string) - Item iso code
    + Values (array [DLC Item]) - List of DLC items


## Faq List [/api/UponorInternet/faq/list{?language}]

+ Parameters
    + language: `de-de` (string, optional) - Language code in which should the content be displayed

### Get all [GET]

+ Response 200 (application/json)

        {
            title: " "
            Faqs: [
                {
                    ID: "{74C75D1E-450A-4C89-AB49-0D1381F8EA68}",
                    Question: "<strong>Sind S-Press PLUS Komponenten kompatibel mit dem bestehenden Uponor Verbundrohrsystem?</strong>",
                    Answer: "Alle S-Press PLUS Komponenten sind vollst&auml;ndig kompatibel mit dem Uponor Verbundrohrsystem. Es werden auch keine anderen Werkzeuge ben&ouml;tigt."
                }
            ]
        }

+ Attributes
    + Title (string) - Title
    + Faqs (array[object])
        + ID (string) - Item ID
        + Question (string) - FAQ Question
        + Answer (string) - FAQ Answer

## Product online catalogue [/api/UponorInternet/poc{?language}]

+ Parameters
    + language: `de-de` (string, optional) - Language code in which should the content be displayed

### Get JSON [GET]

+ Response 200 (application/json)

        {
            Name: "Product online Catalogue",
            IsoCode: "de-DE",
            LastUpdated: "2021-02-16",
            DownloadLink: "https://www.uponor.de/-/media/uponor-internet/poc/dedepocjson.json",
        }

+ Attributes
    + Name (string) - Name
    + IsoCode (string) - Item iso code
    + LastUpdated (string) - Date of last updateDate
    + DownloadLink (string) - Absolute URL to download products JSON

# Data Structures

## News item (object)
+ id (string) - Item unique id
+ title (string) - Item title
+ description (string) - item perex (short description)
+ mediaType (string) - mediaFile type
+ mediaFile (string) - URL to media file
+ mediaFileThumb (string) - URL to media file type
+ url (string) - Item URL

## Sales locator item (object)
+ Company (string) - Company ItemName
+ IdNo (string) - ID NO
+ Person (string) - Person name
+ Street (string) - Street name
+ PoBox (string) - Po Box
+ Zipcode (string) - Zipcode
+ City (string) - City name
+ Region (string) - Region name
+ Country (string) - Country name
+ Phone (string) - Phone number
+ Mobile (string) - Mobile number
+ Fax (string) - Fax number
+ Email (string) - Email address
+ Web (string) - Website address
+ Image (string) - Image URL (relative)
+ MemberShipStartColumn (string) - ???
+ RoleID (string) - ????
+ Plz (string) - ????

## Contact item (object)
+ ContactType (string) - Contact type
+ ContactName (string) - Contact name
+ ContactPhone (string) - Contact Phone
+ ContactFax (string) - Contact Fax
+ ContactMobile (string) - Contact mobile
+ ContactMailLink (object) - Contact Mail ContactMailLink
    + LinkDescription (string) - Link description
    + Mailto (string) - Mailto email address
    + ContactMailSubject (string) - Contact email subject


## Profesionals locator item (object)
+ Name (string) - Name
+ StreetAddress (string) - Street address
+ Zipcode (string) - Zipcode
+ Municipality (string) - Municipality
+ City (string) - City name
+ Country (string) - Country name
+ Telephone (string) - Telephone number
+ Mobile (string) - Mobile number
+ Fax (string) - Fax number
+ WebAddress (string) - Website address
+ TypeName (string) - Type name
+ TypeIcon (string) - Type icon
+ Specialities (array) - Specialitites
+ AdditionalInformation (string) - AdditionalInformation
+ Latitude (string) - Item latitude
+ Longitude (string) - Item longitude

## DLC Item (object)
+ BrochureID (string) - Brochure ID
+ Date (string) - Date
+ Description (string) - Description
+ DocumentType (string) - Document type
+ DownloadLink (string) - Absolute URL to download file
+ FileType (string) - File type (extension)
+ FileTypeIcon (string) - Absolute URL to FileType icon
+ ItemID (string) - Item ID
+ NewIcon (string) - New Icon
+ Size (string) - File size
+ Thumbnail (string) - Absolute URL to file thumbnail
+ Title (string) - File Title





