FORMAT: 1A
HOST: https://www.uponor.de/

# Uponor PRO App - API

Folalowing API is designated to be used with UPONOR PRO APP.

## News [/api/UponorInternet/Newslist/{?language,count}]

### Newslist [GET]

+ Parameters
    + language: `de-de` (string, required) - Language code in which should the news be displayed
    + count (number, optional) - Ammount of items in news

+ Response 200 (application/json)

        {
            status: "1",
            message: "News Get Successfully",
            news: [
                {
                    id: "{FBC4267C-DE68-4874-8AF6-57F551834718}",
                    title: "Zweimal auf dem Treppchen ",
                    description: "Bei einer Leserwahl des Fachportals haustec.de hat Uponor zwei hervorragende zweite Pl&auml;tze erreicht: einmal mit der Einzelraumregelung Smatrix Pulse und einmal mit dem Online-Konfigurator f&uuml;r Verteilerstationen von Heiz- und K&uuml;hlsystemen.&nbsp;",
                    mediaType: "image",
                    createDate: "2021-04-08",
                    mediaFile: "https://www.uponor.de/-/media/country-specific/dach-benelux/news/newsarticle/haustec-leserwahl/haustec-leserwahl-510x320.jpg?h=300&w=400&usecustomfunctions=1&centercrop=1&hash=235C6C1513E44BCDA18A2D2A2E96EFF67A019E92",
                    mediaFileThumb: "https://www.uponor.de/-/media/country-specific/dach-benelux/news/newsarticle/haustec-leserwahl/haustec-leserwahl-510x320.jpg?h=100&w=100&usecustomfunctions=1&centercrop=1&hash=73CDF9EC64556499B01BBFA8FE40B99ECE542579",
                    url: "https://www.uponor.de/unternehmen/news/newsartikel/2021-04-haustec-leserwahl",
                },
            ],
        }

+ Attributes
    + status (string) - Status number (1 = success | 0 = ??)
    + message (string) - Status message
    + news (array [News item]) - list of news items

## Sales Locator [/api/UponorInternet/SalesLocator/{?plz,type}]

+ Parameters
    + plz (number) - ??
    + type (number, optional) - ??

### Get some [GET]

+ Response 200 (application/json)
        
        {
            ItemName: "Sales Locator List"
            Values: [
                        {
                            Company: "Uponor GmbH",
                            IdNo: "67",
                            Person: "Sven Argo",
                            Street: "",
                            PoBox: "",
                            Zipcode: "16761",
                            City: "Hennigsdorf",
                            Region: "",
                            Country: "Deutschland",
                            Phone: "03302 201809",
                            Mobile: "0172 4077723",
                            Fax: "09521 690 99232",
                            Email: "sven.argo@uponor.com",
                            Web: "www.uponor.de",
                            Image: "/-/media/uponor-internet/professional-images/argo-sven.jpg",
                            MembershipStartColumn: "",
                            RoleId: "de-DE",
                            Plz: "1"
                        },
            ]    
        }


+ Attributes
    + ItemName (string) - Item name
    + Values (array [Sales locator item]) - list of news items


## Contacts [/api/UponorInternet/Contact{?language,type}]

+ Parameters
    + language: `de-de` (string, required) - Language code in which should the news be displayed
    + type (enum[string], optional) - Contact type filter
        + Members
            + `academy`
            + `uponorandmore`
            + `customerservice`
            + `technicalhotline`

### Get some [GET]

+ Response 200 (application/json)
        
        {
            Name: "Contact Service",
            IsoCode: "de-DE",
            Values: [
                {
                    ContactType: "academy",
                    ContactName: "Academy",
                    ContactPhone: "+ 49 800 7780050 ",
                    ContactFax: "",
                    ContactMobile: "",
                    ContactMailLink: {
                        LinkDescription: "academy@uponor.com",
                        Mailto: "academy@uponor.com",
                        ContactMailSubject: "Uponor Academy"
                    }
                }
            ],
        }
        
+ Attributes
    + Name (string) - Name
    + IsoCode (string) - Item iso code
    + Values (array [Contact item]) - List of contact service items

# Data Structures

## News item (object)
+ id (string) - Item unique id
+ title (string) - Item title
+ description (string) - item perex (short description)
+ mediaType (string) - mediaFile type
+ mediaFile (string) - URL to media file
+ mediaFileThumb (string) - URL to media file type
+ url (string) - Item URL

## Sales locator item (object)
+ Company (string) - Company ItemName
+ IdNo (string) - ID NO
+ Person (string) - Person name
+ Street (string) - Street name
+ PoBox (string) - Po Box
+ Zipcode (string) - Zipcode
+ City (string) - City name
+ Region (string) - Region name
+ Country (string) - Country name
+ Phone (string) - Phone number
+ Mobile (string) - Mobile number
+ Fax (string) - Fax number
+ Email (string) - Email address
+ Web (string) - Website address
+ Image (string) - Image URL (relative)
+ MemberShipStartColumn (string) - ???
+ RoleID (string) - ????
+ Plz (string) - ????

## Contact item (object)
+ ContactType (string) - Contact type
+ ContactName (string) - Contact name
+ ContactPhone (string) - Contact Phone
+ ContactFax (string) - Contact Fax
+ ContactMobile (string) - Contact mobile
+ ContactMailLink (object) - Contact Mail ContactMailLink
    + LinkDescription (string) - Link description
    + Mailto (string) - Mailto email address
    + ContactMailSubject (string) - Contact email subject


